### PR TITLE
Update Handler.php

### PR DESCRIPTION
**Pull request by gewaechshaus**
Fix for:

PHP Fatal error:  Access level to Ess\M2ePro\Model\Ebay\Order\Shipment\Handler::$activeRecordFactory must be protected (as in class Ess\M2ePro\Model\Order\Shipment\Handler) or weaker in /var/www/html/app/code/Ess/M2ePro/Model/Ebay/Order/Shipment/Handler.php on line 11

Please enable ISSUEs

### CODE REVIEW

**Comment by m2epro** [comment]
this issue was fixed

**Comment by gewaechshaus** [comment]
@m2epro - Thx, maybe you could enable issue tracking on this github project...
I found some other issues related to js minification/merge

**Comment by gewaechshaus** [comment]
There is a subsequent issue while creating shipping on orders imported via m2e:

_Fatal error: Uncaught TypeError: Argument 1 passed to Ess\M2ePro\Model\Order\Shipment\Handler::__construct() must be an instance of Ess\M2ePro\Model\ActiveRecord\Factory, instance of Ess\M2ePro\Helper\Factory given, called in /var/www/html/app/code/Ess/M2ePro/Model/Ebay/Order/Shipment/Handler.php on line 29 and defined in /var/www/html/app/code/Ess/M2ePro/Model/Order/Shipment/Handler.php:24 Stack trace: #0 /var/www/html/app/code/Ess/M2ePro/Model/Ebay/Order/Shipment/Handler.php(29): Ess\M2ePro\Model\Order\Shipment\Handler->__construct(Object(Ess\M2ePro\Helper\Factory), Object(Ess\M2ePro\Model\Factory)) #1 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Ess\M2ePro\Model\Ebay\Order\Shipment\Handler->__construct(Object(Ess\M2ePro\Model\ActiveRecord\Component\Parent\Ebay\Factory), Object(Ess\M2ePro\Model\ActiveRecord\Factory), Object(Ess\M2ePro\Helper\Factory), Object(Ess\M2ePro\Model\Factory)) #2 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framew in /var/www/html/app/code/Ess/M2ePro/Model/Order/Shipment/Handler.php on line 24_

**Comment by gewaechshaus** [comment]
THX for sending out the fixed file...

**Pull request closed without merging**
