### PR TITLE
Fix incorrect tracking details when track list is an array 

### PR DESCRIPTION
**Pull request by tinchodev**
Fix incorrect tracking details when track list is an array instead collection

### CODE REVIEW

**Comment by raisaev** [comment]
@tinchodev, this is a pretty old bug in Magento code. It has been fixed by Magento team quite a long ago. What version of Magento are you using?

**Comment by tinchodev** [comment]
> @tinchodev, this is a pretty old bug in Magento code. It has been fixed by Magento team quite a long ago. What version of Magento are you using?

@raisaev  I'm on 2.2.9

Beyond the array issue,  the track is being picked incorrectly from the track collection, needs to be filtered by Magento Order ID

Before :

`$track = $shipment->getTracksCollection()->getLastItem();`

After : 

```
$track = $shipment
                ->getTracksCollection()
                ->addFieldToFilter('order_id', $order->getMagentoOrderId())
                ->getLastItem();
```
Also if Track instance comes in shipment, there is no need to pull it again from collection.

**Comment by raisaev** [comment]
@tinchodev as I see, you can get wrong tracking details from getTrackingDetails() if it works with a shipment which was not saved yet (as it does not have ID)

\Magento\Sales\Model\Order\Shipment::getTracksCollection
```php
    public function getTracksCollection()
    {
        if ($this->tracksCollection === null) {
            $this->tracksCollection = $this->_trackCollectionFactory->create();

            if ($this->getId()) {
                $this->tracksCollection->setShipmentFilter($this->getId());

                foreach ($this->tracksCollection as $item) {
                    $item->setShipment($this);
                }
            }
        }
        return $this->tracksCollection;
    }

```

**Comment by tinchodev** [comment]
> @tinchodev as I see, you can get wrong tracking details from getTrackingDetails() if it works with a shipment which was not saved yet (as it does not have ID)
> 
> \Magento\Sales\Model\Order\Shipment::getTracksCollection
> 
> ```
>     public function getTracksCollection()
>     {
>         if ($this->tracksCollection === null) {
>             $this->tracksCollection = $this->_trackCollectionFactory->create();
> 
>             if ($this->getId()) {
>                 $this->tracksCollection->setShipmentFilter($this->getId());
> 
>                 foreach ($this->tracksCollection as $item) {
>                     $item->setShipment($this);
>                 }
>             }
>         }
>         return $this->tracksCollection;
>     }
> ```

So.. shipment handler is triggred after the following events as far as i can see:

sales_order_shipment_save_after
sales_shipment_item_save_after
sales_order_shipment_track_save_after

Hence it should be saved... again.. as far as I can see.
Filter by Magento order ID worked for me, also iterate over collection/array (or whatever iterable is  track collection)  to get the proper track.

EDIT : I think that's the problem @raisaev , when shipment is created with the tracking details included sales_order_shipment_save_after will trigger the handler BUT tracking is not on the collection, the track information needs to be get via `$shipment->getData(ShipmentInterface::TRACKS)` 

Best Regards.
Martin Arrua.-

**Comment by raisaev** [comment]
Yes, it is really does not work on 2.2.8 due to the issue in Magento code. They fixed it in 2.3.x branch:
https://github.com/magento/magento2/commit/2307e16105e031c0826d218cf81ffe7949191a0b

As for our side, we can use $shipment->getTracks() instead of $shipment->getTracksCollection() and then that magento bug will not appear.

**Pull request closed without merging**
